### PR TITLE
Ensure UPS service/route bindings are updated with instance

### LINKED ISSUE #2543: cf8 uups -p = PATCH /v3/service_instances/:guid doesn't update service credentials
## Issue

Updating service credentials of a user-provided service doesn't have an effect with cf cli v8 while it works with cf cli v7.

cf8 uses the CF API v3. cf7 still uses CF API v2 for many service related operations.

## Context

CF API version: 3.107.0 = capi release v1.118.0

cf version 8.0.0+e8d41cf8e.2021-09-16
cf7 version 7.2.0+be4a5ce2b.2020-12-10

## Steps to Reproduce

Given an arbitrary deployed testapp, create and bind a user-provided service with some credentials.

```
stephan@WDFN34095835A:~$ cf version
cf version 8.0.0+e8d41cf8e.2021-09-16

stephan@WDFN34095835A:~$ cf cups my-ups -p '{"username":"admin","password":"old-password"}'
Creating user provided service my-ups in org uptime / space test as stephan.merker@sap.com...
OK

stephan@WDFN34095835A:~$ cf bs testapp my-ups
Binding service instance my-ups to app testapp in org uptime / space test as stephan.merker@sap.com...
OK

TIP: Use 'cf restage testapp' to ensure your env variable changes take effect

stephan@WDFN34095835A:~$ cf env testapp | grep password
        "password": "old-password",

```

Update the credentials with cf cli v8:

```
stephan@WDFN34095835A:~$ cf uups my-ups -p '{"username":"admin","password":"new-password"}'
Updating user provided service my-ups in org uptime / space test as stephan.merker@sap.com...
OK

TIP: Use 'cf restage' for any bound apps to ensure your env variable changes take effect

stephan@WDFN34095835A:~$ cf env testapp | grep password
        "password": "old-password",
```

Result: the credentials were not updated.

Now update the credentials with cf cli v7 and see that it works as expected:

```
stephan@WDFN34095835A:~$ cf7 uups my-ups -p '{"username":"admin","password":"new-password"}'
Updating user provided service my-ups in org uptime / space test as stephan.merker@sap.com...
OK

TIP: Use 'cf restage' for any bound apps to ensure your env variable changes take effect
stephan@WDFN34095835A:~$ cf env testapp | grep password
        "password": "new-password",
```

## Expected result

The credentials of the user-provided service can be updated with cf cli v8.

## Current result

`cf uups my-ups -p '{"username":"admin","password":"new-password"}' -v` (cf cli v8) shows that there is a successful CF API request to patch the service instance:

```
REQUEST: [2021-10-18T17:50:59+02:00]
PATCH /v3/service_instances/fd3ba712-04af-43e0-ac8b-49fac38f65c8 HTTP/1.1
Host: api.cf.sap.hana.ondemand.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/8.0.0+e8d41cf8e.2021-09-16 (go1.16.6; amd64 linux)
{
  "credentials": {
    "password": "[PRIVATE DATA HIDDEN]",
    "username": "admin"
  }
}


RESPONSE: [2021-10-18T17:51:00+02:00]
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Mon, 18 Oct 2021 15:51:00 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
X-B3-Spanid: 9f363b936628b758
X-B3-Traceid: 9f363b936628b758
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Ratelimit-Limit: 40000
X-Ratelimit-Remaining: 39998
X-Ratelimit-Reset: 1634575377
X-Runtime: 0.077763
X-Vcap-Request-Id: 2ff8ba78-b4c2-4baa-7ffe-ee928e125bee::1c9d90d3-881e-4186-916f-d592bde71b96
X-Xss-Protection: 1; mode=block
{
  "created_at": "2021-10-18T15:44:55Z",
  "guid": "fd3ba712-04af-43e0-ac8b-49fac38f65c8",
  "last_operation": {
    "created_at": "2021-10-18T15:51:00Z",
    "description": "Operation succeeded",
    "state": "succeeded",
    "type": "update",
    "updated_at": "2021-10-18T15:51:00Z"
  },
  "links": {
    "credentials": {
      "href": "https://api.cf.sap.hana.ondemand.com/v3/service_instances/fd3ba712-04af-43e0-ac8b-49fac38f65c8/credentials"
    },
    "self": {
      "href": "https://api.cf.sap.hana.ondemand.com/v3/service_instances/fd3ba712-04af-43e0-ac8b-49fac38f65c8"
    },
    "service_credential_bindings": {
      "href": "https://api.cf.sap.hana.ondemand.com/v3/service_credential_bindings?service_instance_guids=fd3ba712-04af-43e0-ac8b-49fac38f65c8"
    },
    "service_route_bindings": {
      "href": "https://api.cf.sap.hana.ondemand.com/v3/service_route_bindings?service_instance_guids=fd3ba712-04af-43e0-ac8b-49fac38f65c8"
    },
    "space": {
      "href": "https://api.cf.sap.hana.ondemand.com/v3/spaces/b7c9dfa6-4d92-4851-a3a8-fad6204e51f0"
    }
  },
  "metadata": {
    "annotations": {},
    "labels": {}
  },
  "name": "my-ups",
  "relationships": {
    "space": {
      "data": {
        "guid": "b7c9dfa6-4d92-4851-a3a8-fad6204e51f0"
      }
    }
  },
  "route_service_url": null,
  "syslog_drain_url": null,
  "tags": [],
  "type": "user-provided",
  "updated_at": "2021-10-18T15:50:16Z"
}
```

### PR DESCRIPTION
**Pull request by andy-paine**
## A short explanation of the proposed change:

User provided services provide syslog_drain_url, route_service_url and
credentials directly in the service instance (these come from bindings
for managed services). Updating any of these on the service instance
should be replicated to the service/route bindings also.

## An explanation of the use cases your change solves

In v2, the syslog_drain_url replication was provided by an after_update
hook on the model and the credential replication was provided by a
propagate_instance_credentials action. route_service_url updates do not
work in v2.

In v3, the syslog_drain_url replication still works from the
after_update hook but neither credential nor route_service_url
replication works.

Add 2 new functions to the service instance update transaction in the UPS update action to propagate changes to to the service instance to the service bindings/route bindings of that instance.

## Links to any other associated PRs
CATs PR to demonstrate issue on cf8 https://github.com/cloudfoundry/cf-acceptance-tests/pull/484
Fixes #2543 

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [x] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

**Review by philippthun — APPROVED** [review]

File: app/models/services/user_provided_service_instance.rb [hunk 1]
```diff
@@ -8,6 +8,18 @@ class UserProvidedServiceInstance < ServiceInstance
 
     add_association_dependencies service_bindings: :destroy
 
+    def after_update
```
Comment (monamohebbi) [inline app/models/services/user_provided_service_instance.rb:11]: I know it seems like there is an existing pattern of doing this in the after update, and to be fair I'm not too familiar with the services corners of the API and what patterns exist there that we wish to propagate forward, but I do know that a stylistic change we tried to push forward in the V3 API in general was to move away from relying on async model hooks (see these bullet point 3 from these [notes](https://github.com/cloudfoundry/cloud_controller_ng/wiki/Notes-on-V3-Architecture#preamble)).

What are your thoughts on moving this action to the update action, maybe in this [transaction](https://github.com/cloudfoundry/cloud_controller_ng/blob/4c355140498a284662f589bbac4efc920ab2788f/app/actions/service_instance_update_user_provided.rb#L30-L34), using the updates defined [here](https://github.com/cloudfoundry/cloud_controller_ng/blob/4c355140498a284662f589bbac4efc920ab2788f/app/actions/service_instance_update_user_provided.rb#L19-L20) as a conditional.

**Review by monamohebbi — COMMENTED** [review]
This looks good to me over all. I have some thoughts on patterns we hope to maintain and would like to hear your perspectives as people who have worked on the services code quite a lot recently.

File: app/models/services/user_provided_service_instance.rb (hunk 1 above)
Comment (andy-paine) [reply app/models/services/user_provided_service_instance.rb]: Ah I hadn't seen that doc. I was going for consistency with v2 but I guess since it uses a bit of an anti-pattern we are moving away from that! I've pushed a change doing as recommended and removed the other commit. This leaves the route_service_url update not working in v2 but it has been like that for a long time and getting this v3 endpoint working (esp. for credentials) is more important right now I think

File: app/actions/service_instance_update_user_provided.rb [hunk 2]
```diff
@@ -30,6 +30,8 @@ def update(service_instance, message)
       service_instance.db.transaction do
         original_service_instance = service_instance.dup
         service_instance.save_with_new_operation(updates, last_operation)
+        update_service_bindings(service_instance, updates) if updates.key?(:credentials) || updates.key?(:syslog_drain_url)
+        update_route_bindings(service_instance, updates) if updates.key? :route_service_url
```
Comment (philippthun) [inline app/actions/service_instance_update_user_provided.rb:34]: [Minor] I would prefer a consistent check for existing entries in `updates`. Currently there are three (two and a half) different variants:
```
if updates.key?(:credentials)
if updates.key? :route_service_url
if updates[:syslog_drain_url]
```

**Review by philippthun — APPROVED** [review]
