### PR TITLE
Strictly validate page and per_page pagination options

### LINKED ISSUE #2194: Paginated v3 endpoints do not properly validate that the page and per_page query parameters are integers
## Issue
Paginated `v3` endpoints do not properly validate that the `page` and `per_page` query parameters are integers

## Context
When querying a paginated `v3` endpoint, the page parameter is only loosely validated. Values such as `page=1.5` or `page=1.abcd` are accepted (and converted to integer 1)

## Steps to Reproduce
`cf curl /v3/organizations?page=1.abcd`

## Expected result
400 Bad Request with useful error message stating that `page` should be a positive integer

## Current result
The first page of results is returned

## Possible Fix
Strictly validate the `page` and `per_page` query parameters

### PR DESCRIPTION
**Pull request by andy-paine**
Existing validation just compared the value of the input `.to_i` against
the limits. This method means that floats and strings such as `1.abcd`
get treated as valid integers and so are accepted by the API. By using
the Rails validation methods we can get stricter controls over what
is allowable and save writing custom validation functions

Fixes #2194 

A short explanation of the proposed change:
* Use Rails builtin validation for v3 pagination query params

An explanation of the use cases your change solves
* Users submitting non-integer `page` parameters should get 400 errors rather than fuzzy integer casts

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng#cf-acceptance-tests-cats)

### CODE REVIEW

File: lib/cloud_controller/paging/pagination_options.rb [hunk 1]
```diff
@@ -7,29 +7,49 @@ class PaginationOptions
...
-    attr_writer :order_by, :order_direction, :default_order_by
-    attr_accessor :page, :per_page
+    attr_writer :order_by, :order_direction, :default_order_by, :page, :per_page
+
+    validates_numericality_of :page_string,
+      allow_nil: true,
+      only_integer: true,
+      greater_than_or_equal_to: 1,
+      message: 'must be a positive integer'
+    validates_numericality_of :per_page_string,
```
Comment (sethboyles) [inline lib/cloud_controller/paging/pagination_options.rb:20]: why validate on `per_page_string` rather than `per_page`?

File: app/messages/list_message.rb [hunk 2]
```diff
@@ -25,6 +27,7 @@ def initialize(params={})
       params = params.symbolize_keys
       @pagination_params = params.slice(*ALLOWED_PAGINATION_KEYS)
       @pagination_options = PaginationOptions.from_params(params)
+      invalid_param!(@pagination_options.errors.full_messages) unless @pagination_options.valid?
```
Comment (sethboyles) [inline app/messages/list_message.rb:30]: A Message class shouldn't need to require a controller or have access to the `invalid_param!` method.  Generally, messages should be informative while the controller actually decides what to do with any errors reported by the message.  Please see https://github.com/cloudfoundry/cloud_controller_ng/wiki/Notes-on-V3-Architecture#controllers for more details

File: spec/unit/lib/cloud_controller/paging/pagination_options_spec.rb [hunk 3]
```diff
@@ -115,31 +115,66 @@ module VCAP::CloudController
...
+        expect(pagination_options.per_page).to eq(per_page.to_i)
         expect(pagination_options.order_by).to eq(order_by)
         expect(pagination_options.order_direction).to eq(order_direction)
       end
     end
 
     describe 'validations' do
       context 'when page is not an integer' do
-        let(:params) { { page: 3.5 } }
+        let(:params) { { page: '3.5' } }
```
Comment (sethboyles) [inline spec/unit/lib/cloud_controller/paging/pagination_options_spec.rb:127]: what's the behavior for a case like `page: '3.0'` ?

**Comment by sethboyles** [comment]
Hi @andy-paine , 

Thank you for the PR!

It's a bit unfortunate this behavior this PR fixes has existed for so long and affects so much of the codebase.  I am wondering if this might be a breaking change for any existing clients which have, for better or worse, relied on the loose validation we have had for pagination options.  

Can you explain a little bit as to why you would like to see this fixed?

**Comment by andy-paine** [comment]
@sethboyles Thanks for your comment on the PR.

Initially we wanted to change this because we see 500 Errors when `page multiplied by `per_page` is exceeding the database bigint limit. Just on coincidence we also experienced that the unittests of the page parameter validation is reversed. Instead of testing that no string can be passed it tested that a string can be passed.
So we also tried to make the parameter validation follow the documented behaviour.
Understandably a user that supplies a float like `3.0` may be hit by the change.
However both parameters are explicitly documented as an integer https://v3-apidocs.cloudfoundry.org/version/3.99.0/#get-an-app.

So we can now either fix both things (validate parameters as documented and enforce maximum)
or we can just add the validation for the maximum value and keep strings allowed.

It would feel more correct if a user is really just able to pass an integer instead of floats and strings.

File: lib/cloud_controller/paging/pagination_options.rb (hunk 1 above)
Comment (andy-paine) [reply lib/cloud_controller/paging/pagination_options.rb:20]: The validator tests a function however since we call to_i we need to validate the value of page before it gets casted to an integer.

File: app/messages/list_message.rb (hunk 2 above)
Comment (andy-paine) [reply app/messages/list_message.rb:30]: That's really useful to know, thanks for the link. Looks like we can just add a validator to the list message class that will call the pagination options validate method and add in any errors found so we don't need to use the `invalid_param` method and it is up to the calling controller to throw the correct exception 👍

File: spec/unit/lib/cloud_controller/paging/pagination_options_spec.rb (hunk 3 above)
Comment (andy-paine) [reply spec/unit/lib/cloud_controller/paging/pagination_options_spec.rb:127]: Looks like this is invalid too which is a bit unfortunate but seems to be the behaviour of the `only_integer` flag to the validator

**Comment by MarcPaquette** [comment]
Hi @andy-paine,

We took a look at this PR, and there's quite a bit of goodness here.  We see  value in the limiting of the page size and feel it adds to the stability of the CC overall.  The input sanitation is a bit concerning for us as our users have reacted in a negative way to breaking changes to existing behavior without ample notice. 

With all that being said, would it be possible to scale back this code to just include the page limits, and omit the input validation till another time when such changes are necessary to migitage a specific pain point for users?

Thanks,
@sweinstein22  & @MarcPaquette

**Comment by andy-paine** [comment]
Hi @MarcPaquette - thanks for taking a look! We are really just looking to remove the 500 errors so we can drop the strict validation if needed. Rather than reinvent the wheel of validation, I've just added a new function and some tests to the existing validation to check that the page sizes aren't enormous. This should stop the DB getting queried with an `OFFSET` that it can't handle which should hopefully remove the 500 error.
