### PR TITLE
Fix db encryption key loading

### LINKED ISSUE #3908: DB encryption key loaded incorrectly in DB migration
Thanks for submitting an issue to `cloud_controller_ng`. We are always trying to improve! To help us, please fill out the following template.

## Issue

[db.rake](https://github.com/cloudfoundry/cloud_controller_ng/blob/3d09a707b253acbdf54dff659a329f4267c840f3/lib/tasks/db.rake#L127) and [dbmigrator](https://github.com/cloudfoundry/cloud_controller_ng/blob/3d09a707b253acbdf54dff659a329f4267c840f3/lib/cloud_controller/db_migrator.rb#L8) use old method of loading the db encryption key.

`VCAP::CloudController::Encryptor.db_encryption_key = RakeConfig.config.get(:db_encryption_key)`

## Context
To ensure full db encryption key setup db key load should happen like it does in, [`@config.configure_components`](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/lib/cloud_controller/config.rb#L110-L116) should be called on db connection.

```
      Encryptor.db_encryption_key = get(:db_encryption_key)

      if get(:database_encryption)
        Encryptor.database_encryption_keys = get(:database_encryption)[:keys]
        Encryptor.current_encryption_key_label = get(:database_encryption)[:current_key_label]
        Encryptor.pbkdf2_hmac_iterations = get(:database_encryption)[:pbkdf2_hmac_iterations]
      end
```
@Samze discovered this [here](https://github.com/cloudfoundry/cloud_controller_ng/pull/3894#discussion_r1693336141), verified by @tcdowney, details in link

## Expected result

Update [db.rake](https://github.com/cloudfoundry/cloud_controller_ng/blob/3d09a707b253acbdf54dff659a329f4267c840f3/lib/tasks/db.rake#L127) and [dbmigrator](https://github.com/cloudfoundry/cloud_controller_ng/blob/3d09a707b253acbdf54dff659a329f4267c840f3/lib/cloud_controller/db_migrator.rb#L8)  to use correct db encryption setup

## Current result

Deprecated way of loading key is used

[include relevant logs]

## Possible Fix

A helper method [`def load_db_encryption_key`](https://github.com/cloudfoundry/cloud_controller_ng/pull/3894/files#diff-7d804c57362f2c9d1da7ef32e969254a711f6529952c31b997b634253f6c23f8R120) was included in config as part of the PR where this issue was found that can be used to set up db encryption.

## `name of issue` screenshot

[if relevant, include a screenshot]

### PR DESCRIPTION
**Pull request by Samze**
Currently we only load from the old decrepcated method of encryption keys. This fixes this to use all encrytpion key methods specified in https://github.com/cloudfoundry/capi-release/blob/develop/jobs/cloud_controller_ng/spec#L773-L782.

Fixes #3908

* [x] I have reviewed the [contributing guide](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/CONTRIBUTING.md)

* [x] I have viewed, signed, and submitted the Contributor License Agreement

* [x] I have made this pull request to the `main` branch

* [x] I have run all the unit tests using `bundle exec rake`

* [ ] I have run [CF Acceptance Tests](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/spec/README.md#cf-acceptance-tests-cats)

### CODE REVIEW

File: lib/cloud_controller/db_migrator.rb [hunk 1]
```diff
@@ -5,7 +5,7 @@ class DBMigrator
   SEQUEL_MIGRATIONS = File.join(MIGRATIONS_DIR, 'migrations')
 
   def self.from_config(config, db_logger)
-    VCAP::CloudController::Encryptor.db_encryption_key = config.get(:db_encryption_key)
+    config.load_db_encryption_key
```
Comment (xandroc) [inline lib/cloud_controller/db_migrator.rb:8]: clean implementation, nice!

**Review by xandroc — APPROVED** [review]
looks good, lgtm!

**Review by a-b — APPROVED** [review]
LGTM
